### PR TITLE
Zink : Turnip Driver 

### PR DESCRIPTION
**Pull request by Vera-Firefly**
Add Turnip driver to zink renderer

### CODE REVIEW

**Comment by didntpenguin** [comment]
look cool,love your work :3333

**Comment by artdeell** [comment]
As always, copied verbatim from Pojav.

**Comment by Vera-Firefly** [comment]
> As always, copied verbatim from Pojav.

So?What's wrong with that?

**Comment by artdeell** [comment]
> So?What's wrong with that?

No, it's just funny how everything now is just copied from pojav. Nothing new is made, except by us.

**Comment by Vera-Firefly** [comment]
> > So?What's wrong with that?
> 
> No, it's just funny how everything now is just copied from pojav. Nothing new is made, except by us.

It's not for everyone, as you can see, it's more suitable for Chinese babies

**Comment by MoonKnightBhai** [comment]
I am just reading you peoples convo :] don't mind me

**Comment by artdeell** [comment]
> Since you have such a big problem with it, what is the purpose of your open source? @artdeell

I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.

**Comment by MoonKnightBhai** [comment]
> I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.

And youtube says ctrl c and Ctrl v are important for coding 💀 learning new stuff every day

**Comment by root-S7** [comment]
> > Since you have such a big problem with it, what is the purpose of your open source? @artdeell
> 
> I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.

Recognize

**Comment by root-S7** [comment]
> > Since you have such a big problem with it, what is the purpose of your open source? @artdeell
> 
> I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.

Another project ＂copy＂ pojavlauncher project
https://github.com/Coloryr/ColorMC.Android

**Comment by Vera-Firefly** [comment]
> > Since you have such a big problem with it, what is the purpose of your open source? @artdeell
> 
> I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.
Maybe you should ask the developers of this app,I don't know what the contradiction is.

**Comment by LegacyGamerHD** [comment]
> > > Since you have such a big problem with it, what is the purpose of your open source? @artdeell
> > 
> > 
> > I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.
> > Maybe you should ask the developers of this app,I don't know what the contradiction is.

if can vera try joing the  discord  https://discord.gg/wZJ75TS9

**Comment by Vera-Firefly** [comment]
> > > > Since you have such a big problem with it, what is the purpose of your open source? @artdeell
> > > 
> > > 
> > > I always wanted for the open source of Pojav would be used for other cool and interesting projects, which is the intent. Yet another Minecraft launcher, imo, is not a cool project as you don't even have to do much yourself, just ctrl-c and ctrl-v the hard part and design a UI around it.
> > > Maybe you should ask the developers of this app,I don't know what the contradiction is.
> 
> if can vera try joing the discord https://discord.gg/wZJ75TS9

I have a problem that I can't accept.

**Pull request merged**
